@base = http://localhost:5085

POST {{base}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "dima",
    "password": "123456"
}

###
POST {{base}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "email": "dima",
    "password": "123456",
    "firstName": "Dima",
    "lastName": "Kovalenko",
    "sex": 0,
    "birthDate": "1995-01-01"
}

###
GET {{base}}/api/auth/test
Accept: application/json

###